import sys,json,re
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
base=sys.argv[1]
captures=Path(sys.argv[2]);captures.mkdir(parents=True,exist_ok=True)
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,args=['--disable-webgl'])
    context=browser.new_context(viewport={'width':1440,'height':1000},reduced_motion='reduce',color_scheme='dark')
    page=context.new_page();errors=[]
    page.on('pageerror',lambda error:errors.append(str(error)))
    page.goto(base+'/login');page.get_by_label('Email',exact=True).fill('cms-review@example.test');page.get_by_label('Password',exact=True).fill('ReviewPassword!42');page.get_by_role('button',name='Sign In',exact=True).click()
    expect(page.get_by_role('heading',name='Studio overview')).to_be_visible()
    page.screenshot(path=str(captures/'cms-desktop.png'),full_page=True)
    assert page.evaluate('history.state.page instanceof ArrayBuffer'), 'Private page history should be encrypted'
    page.get_by_role('link',name='Pages & content',exact=True).click()
    expect(page.get_by_role('heading',name='Homepage',exact=True)).to_be_visible()
    expect(page.locator('html')).to_have_class('dark')
    expect(page.get_by_label('Helix caption',exact=True)).to_have_css('background-color','rgb(255, 255, 255)')
    expect(page.get_by_label('Helix caption',exact=True)).to_have_css('color','rgb(32, 37, 30)')
    page.get_by_label('Banner heading (one line per row)',exact=True).fill('Browser tested heading')
    page.get_by_role('button',name='Save draft',exact=True).first.click()
    expect(page.get_by_role('status')).to_contain_text('Draft saved')
    visitor=browser.new_page(reduced_motion='reduce')
    visitor.goto(base+'/?preview=1');expect(visitor.locator('h1')).to_contain_text('Built to be')
    with page.expect_popup() as popup:
        page.get_by_role('link',name='Preview saved draft').click()
    preview=popup.value;preview.wait_for_load_state();expect(preview.locator('h1')).to_have_text('Browser tested heading');preview.close()
    page.once('dialog',lambda dialog:dialog.accept())
    page.get_by_role('button',name='Publish',exact=True).click()
    expect(page.get_by_role('status')).to_contain_text('Published.')
    visitor.reload();expect(visitor.locator('h1')).to_have_text('Browser tested heading');visitor.close()
    page.screenshot(path=str(captures/'cms-editor-desktop.png'),full_page=True)
    page.locator('#cms-section').select_option('about');expect(page.get_by_role('heading',name='About & skills',exact=True)).to_be_visible()
    expect(page.get_by_label('Biography (blank line between paragraphs)',exact=True)).not_to_have_value('')
    page.get_by_role('link',name='Enquiries',exact=True).click()
    page.locator('summary').filter(has_text='Sample enquiry').click()
    page.get_by_label('Private notes').fill('Browser verified follow-up note')
    page.get_by_label('Status',exact=True).select_option('read')
    page.get_by_role('button',name='Save enquiry',exact=True).click()
    expect(page.get_by_role('status')).to_contain_text('Enquiry updated')
    page.screenshot(path=str(captures/'cms-inbox-desktop.png'),full_page=True)
    page.get_by_role('link',name='Analytics',exact=True).click()
    expect(page.get_by_role('heading',name='Analytics',exact=True)).to_be_visible()
    page.get_by_label('Period',exact=True).select_option('90')
    page.get_by_role('button',name='Apply filters').click()
    expect(page).to_have_url(re.compile('days=90'))
    cells=page.locator('.an-calendar-cell')
    expect(cells).to_have_count(90)
    cells.first.focus();page.keyboard.press('ArrowRight')
    expect(cells.nth(7)).to_be_focused()
    expect(page.locator('.an-calendar-detail')).to_have_text(cells.nth(7).get_attribute('aria-label'))
    page.keyboard.press('End');expect(cells.last).to_be_focused()
    expect(page.locator('.an-calendar-detail')).to_contain_text('Today so far')
    assert cells.evaluate_all('(els) => els.every(el => { const r = el.getBoundingClientRect(); return Math.abs(r.width - r.height) < 1; })'), 'Calendar cells must be square'
    assert cells.evaluate_all('(els) => els.some(el => el.dataset.level === "0") && els.some(el => el.dataset.level === "4")'), 'Calendar must distinguish zero and peak activity'
    page.locator('.an-calendar').screenshot(path=str(captures/'cms-activity-calendar-desktop.png'))
    page.set_viewport_size({'width':390,'height':844})
    page.locator('.an-calendar').screenshot(path=str(captures/'cms-activity-calendar-mobile.png'))
    assert page.locator('.an-calendar-scroll').evaluate('(el) => el.scrollWidth <= el.clientWidth'), '90-day calendar must fit mobile without horizontal scrolling'
    expect(cells.first).to_have_css('animation-name','none')
    page.set_viewport_size({'width':1440,'height':1000})
    page.get_by_label('Period',exact=True).select_option('7')
    page.get_by_role('button',name='Apply filters').click()
    expect(page).to_have_url(re.compile('days=7'))
    expect(page.get_by_label('Period',exact=True)).to_have_value('7')
    expect(page.locator('.an-calendar-cell')).to_have_count(7)
    with page.expect_download() as download:
        page.get_by_role('button',name='Export daily CSV').click()
    assert download.value.suggested_filename=='analytics-7-days.csv'
    page.get_by_role('button',name='Bar chart',exact=True).click()
    expect(page.get_by_role('button',name='Bar chart',exact=True)).to_have_attribute('aria-pressed','true')
    page.locator('#traffic-metric').select_option('clicks')
    page.locator('.an-plot svg').focus();page.keyboard.press('ArrowLeft')
    expect(page.locator('.an-chart-readout')).to_contain_text('clicks')
    page.get_by_role('button',name='Area chart',exact=True).click()
    page.locator('#traffic-metric').select_option('views')
    page.screenshot(path=str(captures/'cms-analytics-desktop.png'),full_page=True)
    page.get_by_role('button',name='Engagement',exact=True).click()
    expect(page.get_by_role('heading',name='What holds attention')).to_be_visible()
    page.screenshot(path=str(captures/'cms-analytics-engagement.png'),full_page=True)
    page.get_by_role('button',name='Content & actions',exact=True).click()
    expect(page.get_by_role('heading',name='Page performance')).to_be_visible()
    page.screenshot(path=str(captures/'cms-analytics-content.png'),full_page=True)
    page.set_viewport_size({'width':390,'height':844})
    page.get_by_role('button',name='Audience',exact=True).click()
    page.screenshot(path=str(captures/'cms-analytics-mobile.png'),full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Analytics mobile overflow'
    page.set_viewport_size({'width':1440,'height':1000})
    page.get_by_role('link',name='Media library',exact=True).click()
    expect(page.get_by_role('heading',name='Media library',exact=True)).to_be_visible()
    expect(page.locator('.filepond--root')).to_have_count(2)
    expect(page.locator('.filepond--drop-label').first).to_have_css('opacity', '1')
    expect(page.locator('.filepond--label-action').first).to_be_visible()
    expect(page.locator('.filepond--label-action').last).to_be_visible()
    page.screenshot(path=str(captures/'cms-media-desktop.png'),full_page=True)
    page.locator('#media-project').select_option(label='Sample browser test project')
    expect(page.get_by_role('heading',name='Project images',exact=True)).to_be_visible()
    page.get_by_role('link',name='Projects',exact=True).click()
    page.get_by_role('button',name='Add project',exact=True).click()
    page.locator('dialog[open]').get_by_label('Title',exact=True).fill('New draft from browser')
    page.locator('dialog[open]').get_by_label('Category',exact=True).fill('Web Development')
    page.locator('dialog[open]').get_by_label('Description',exact=True).fill('Created by the isolated browser test.')
    page.get_by_role('button',name='Create Project',exact=True).click()
    expect(page.get_by_role('status')).to_contain_text('Project created')
    page.keyboard.press('Escape')
    page.screenshot(path=str(captures/'cms-projects-desktop.png'),full_page=True)
    page.get_by_role('link',name='Overview',exact=True).click()
    expect(page.get_by_role('heading',name='Studio overview')).to_be_visible()
    page.set_viewport_size({'width':390,'height':844})
    expect(page.get_by_role('button',name='Page views',exact=True)).to_have_css('color','rgb(244, 245, 239)')
    page.screenshot(path=str(captures/'cms-mobile.png'),full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Mobile horizontal overflow'
    page.get_by_role('button',name='Toggle CMS navigation').click()
    page.get_by_role('link',name='Pages & content',exact=True).click()
    expect(page.get_by_role('heading',name='Homepage',exact=True)).to_be_visible()
    page.screenshot(path=str(captures/'cms-editor-mobile.png'),full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Mobile editor overflow'
    page.get_by_role('button',name='Toggle CMS navigation').click()
    page.get_by_role('link',name='Account & security',exact=True).click()
    page.get_by_label('Current password',exact=True).fill('ReviewPassword!42')
    page.get_by_label('New password',exact=True).fill('ChangedPassword!42')
    page.get_by_label('Confirm new password',exact=True).fill('ChangedPassword!42')
    page.get_by_role('button',name='Update password & sign out').click()
    expect(page.get_by_role('heading',name='Admin Login',exact=True)).to_be_visible()
    assert not errors, json.dumps(errors)
    print('CMS browser workflows passed: draft privacy, preview, publish, inbox, charts, media UI, project creation, mobile layouts, encrypted history, password change.')
    browser.close()
